apiVersion: v1
kind: Service
metadata:
  labels:
    app: linux
  name: linux-service
spec:
  ports:
  - port: 8096 #change to 80
    protocol: TCP
    targetPort: 8096 #change to 80
  selector:
    app: solar-system
  type: LoadBalancer
