apiVersion: v1
kind: Service
metadata:
  labels:
    app: linux
  name: linux-service
spec:
  ports:
  - port: 3579 #change to 80
    targetPort: 3579 #change to 80
  selector:
    app: linux
  type: LoadBalancer
